name: health_wallet
description: "HealthWallet.me"
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.5

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Routing
  auto_route: ^7.8.4

  # Network
  dio: ^5.4.1

  # Local Storage
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3


  # UI
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.14.3

  # Utils
  intl: ^0.20.2
  logger: ^2.0.2+1
  package_info_plus: ^8.0.0
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  local_auth: ^2.1.7
  reorderable_grid_view: ^2.2.8
  url_launcher: ^6.2.5
  android_intent_plus: ^5.0.2
  fhir_r4: ^0.4.2
  file_picker: ^8.3.7
  path: ^1.9.1
  share_plus: ^11.0.0
  network_info_plus: ^6.0.1
  mobile_scanner: ^7.0.1
  onboarding_overlay: ^3.2.2

  fhir_ips_export:
    git:
      url: ssh://git@git.techstackapps.com:2822/mobile/health-wallet/fhir-ips-export.git
  flutter_doc_scanner: ^0.0.16
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.15.0
  pdfx: ^2.9.2
  printing: ^5.13.4
  flutter_pdfview: ^1.4.3
  receive_sharing_intent: ^1.8.1
  # cunning_document_scanner: ^1.3.1
  flutter_gemma: ^0.11.3
  string_similarity: ^2.1.1
  bloc_concurrency: ^0.2.5
  collection: ^1.19.1
  uuid: ^4.5.1
  envied: ^1.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  custom_lint: ^0.7.0
  bloc_lint: ^0.1.0

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  flutter_gen_runner: ^5.4.0
  drift_dev: ^2.15.0

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  golden_toolkit: ^0.15.0
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/
    - assets/favIcons/
    - assets/onboarding/
    - assets/font/matter-font/

  fonts:
    - family: Matter
      fonts:
        - asset: assets/font/matter-font/Matter-Regular.ttf
        - asset: assets/font/matter-font/Matter-RegularItalic.ttf
          style: italic
        - asset: assets/font/matter-font/Matter-Light.ttf
          weight: 300
        - asset: assets/font/matter-font/Matter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/matter-font/Matter-Medium.ttf
          weight: 500
        - asset: assets/font/matter-font/Matter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/matter-font/Matter-SemiBold.ttf
          weight: 600
        - asset: assets/font/matter-font/Matter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/matter-font/Matter-Bold.ttf
          weight: 700
        - asset: assets/font/matter-font/Matter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/matter-font/Matter-Heavy.ttf
          weight: 900
        - asset: assets/font/matter-font/Matter-HeavyItalic.ttf
          weight: 900
          style: italic

flutter_gen:
  output: lib/gen
  line_length: 80

  integrations:
    flutter_svg: true
